In [4]:
import numpy as np
import pandas as pd

In [5]:
df = pd.read_csv(r"C:\Users\24SRV\OneDrive\Desktop\brazilian_ecommerce_project\data\raw\olist_order_reviews_dataset.csv")
df.head()

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN,2018-01-18 00:00:00,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,NaN,2018-03-10 00:00:00,2018-03-11 03:05:13
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,NaN,2018-02-17 00:00:00,2018-02-18 14:36:24
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,NaN,Recebi bem antes do prazo estipulado.,2017-04-21 00:00:00,2017-04-21 22:02:06
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,NaN,Parabéns lojas lannister adorei comprar pela I...,2018-03-01 00:00:00,2018-03-02 10:26:53

In [6]:
df.isna().sum()

review_id                      0
order_id                       0
review_score                   0
review_comment_title       87656
review_comment_message     58247
review_creation_date           0
review_answer_timestamp        0
dtype: int64

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99224 entries, 0 to 99223
Data columns (total 8 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   review_id                99224 non-null  object
 1   order_id                 99224 non-null  object
 2   review_score             99224 non-null  int64
 3   review_comment_title     11566 non-null  object
 4   review_comment_message   40950 non-null  object
 5   review_creation_date     99224 non-null  object
 6   review_answer_timestamp  99224 non-null  object
 7   has_comment              99224 non-null  bool
dtypes: bool(1), int64(1), object(6)
memory usage: 5.4+ MB

In [7]:
df.duplicated().sum()

0

In [8]:
df[~df["review_score"].between(1, 5)]

Empty DataFrame
Columns: [review_id, order_id, review_score, review_comment_title, review_comment_message, review_creation_date, review_answer_timestamp]
Index: []

In [9]:
import numpy as np

comment_cols = [
    "review_comment_title",
    "review_comment_message"
]

for col in comment_cols:
    df[col] = df[col].replace(
        r"^\s*$", np.nan, regex=True
    )

In [11]:
df["has_comment"] = df["review_comment_message"].notna()

In [12]:
df["has_comment"]

0        False
1        False
2        False
3         True
4         True
         ...
99219    False
99220    False
99221     True
99222    False
99223     True
Name: has_comment, Length: 99224, dtype: bool

In [14]:
date_cols = [
    "review_creation_date",
    "review_answer_timestamp"
]

for col in date_cols:
    df[col] = pd.to_datetime(df[col], errors="coerce")

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99224 entries, 0 to 99223
Data columns (total 8 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   review_id                99224 non-null  object
 1   order_id                 99224 non-null  object
 2   review_score             99224 non-null  int64
 3   review_comment_title     11566 non-null  object
 4   review_comment_message   40950 non-null  object
 5   review_creation_date     99224 non-null  datetime64[ns]
 6   review_answer_timestamp  99224 non-null  datetime64[ns]
 7   has_comment              99224 non-null  bool
dtypes: bool(1), datetime64[ns](2), int64(1), object(4)
memory usage: 5.4+ MB

In [17]:
df.to_csv("../data/cleaned/order_reviews_cleaning.csv", index=False)